### ISSUE TITLE
How to add kerchunked datasets to intake catalog

### ISSUE THREAD

**Issue by pnorton-usgs** [hytest-org/hytest#136]
How do I properly add kerchunked datasets to intake catalog?

**Comment by rsignell-usgs** [comment]
Great question @pnorton-usgs -- they can be tricky, as the reference file JSON and the source NetCDF or GRIB2 files can live in different locations (e.g. different buckets) and have different permissions!

Here's an example from the [great @peterm790 Medium article on Kerchunk](https://medium.com/pangeo/accessing-netcdf-and-grib-file-collections-as-cloud-native-virtual-datasets-using-kerchunk-625a2d0a9191):
``` 
sources:
  ERA5-Kerchunk-1979-2022:
    driver: intake_xarray.xzarr.ZarrSource
    description: 'ERA5-pds Kerchunked virtual dataset'
    metadata:
      tags:
      - reanalysis
      url: https://registry.opendata.aws/ecmwf-era5/
    args:
      consolidated: False
      urlpath: "reference://"
      storage_options:
        fo: 's3://esip-qhub-public/ecmwf/ERA5_1979_2022_multivar.json.zst'
        remote_options:
          anon: true
        remote_protocol: s3
        ref_storage_args: 
          compression: 'zstd'
  ERA5-Kerchunk-2020-2022:
    driver: intake_xarray.xzarr.ZarrSource
    description: 'ERA5-pds Kerchunked virtual dataset'
    metadata:
      tags:
      - reanalysis
      url: https://registry.opendata.aws/ecmwf-era5/
    args:
      consolidated: False
      urlpath: "reference://"
      storage_options:
        fo: 's3://esip-qhub-public/ecmwf/ERA5_2020_2022_multivar.json.zst'
        remote_options:
          anon: truemote_protocol: s3
        ref_storage_args:
          compression: 'zstd'
```
And here's my IOOS intake catalog:
```
sources:
  COAWST-Archive:
    driver: intake_xarray.xzarr.ZarrSource
    description: 'COAWST Forecast Archive'
    args:
      urlpath: "reference://"
      consolidated: false
      storage_options:
        target_options:
          anon: true
          client_kwargs: {'endpoint_url': 'https://mghp.osn.xsede.org'}
        fo: 's3://rsignellbucket1/COAWST/archive.json'
        remote_options:
          anon: true
          client_kwargs: {'endpoint_url': 'https://mghp.osn.xsede.org'}
        remote_protocol: "s3"
  LiveOcean-Archive:
    driver: intake_xarray.xzarr.ZarrSource
    description: 'LiveOcean Forecast Archive'
    args:
      urlpath: "reference://"
      consolidated: false
      storage_options:
        fo: 's3://esip-qhub-public/LiveOcean/LiveOcean_reference.json'
        target_options:
          anon: true
          skip_instance_cache: True
        remote_options:
          account_name: "pm2"
          anon: true
          skip_instance_cache: True
        remote_protocol: "abfs"
```
In the above catalogs, the key things are the:
* storage_options: for the source files, like the NetCDF or GRIB files
* target_options: for the JSON referenceFileSystem file.
