### ISSUE TITLE
Build a hytest Docker Container 

### ISSUE THREAD

**Issue by gzt5142** [hytest-org/hytest#138]
This issue spawned as a sub-task from #100 ... 

Build a 'standardized' container with the necessary conda environment. This is for use with: 
* `kbatch` (we need this to do automated notebook actions)
* `singularity` 
* `shifter`

We might be able to find a use for this where the entry point to the container is the jupyter server itself.... TBD.  The *real* reason we need this is for `kbatch` submissions.

https://github.com/hytest-org/hytest/issues/100#issuecomment-1323354520

Notes: 
* https://github.com/jupyterhub/repo2docker
* https://github.com/jupyterhub/repo2docker-action
* https://github.com/iameskild/repo2registry

**Comment by gzt5142** [comment]
So it looks like the repo-->docker-image bits are actually supplied by the jupyterhub people, which makes good sense. I was initially skeptical about a repo owned by `iameskild`.. but it looks like it will be an excellent model from which to build our customized container build.

**Comment by gzt5142** [comment]
OK... good news... can build a basic container and publish to the github container registry (ghcr.io) using a github action.   This is what I am using for the action config: 
```
name: Build Docker Container and Push to Registry
on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: gzt5142/htdemo

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: "Build, Push image"
        uses: jupyterhub/repo2docker-action@master
        with:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_REGISTRY: ${{ env.REGISTRY }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
```

Note that I removed the need to use the docker sign-in (which is an element of the source material from which I derived the above).  Because our registry and this repo both live on github, the login and secret information is common -- no need to set up extra secrets or logins.
